name: Sync Upstream

on:
  schedule:
    # Executa diariamente às 05:00 UTC (ajuste conforme necessário)
    - cron: '0 5 * * *'
  # Permite acionar manualmente pela interface do GitHub
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Checkout do código do seu fork
      - name: Checkout fork
        uses: actions/checkout@v4

      # Passo 2: Configurar Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"

      # Passo 3: Sincronizar com o repositório upstream
      - name: Merge upstream changes
        run: |
          # Adiciona o remote upstream
          git remote add upstream https://github.com/BoringBoredom/UEFI-Editor.git
          # Busca as alterações do upstream
          git fetch upstream
          # Faz merge das alterações do branch principal (ex: master) do upstream
          git merge upstream/master --no-edit

      # Passo 4: Envia as alterações para o seu fork
      - name: Push changes
        run: |
          git push origin master
